language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

script:
  - yarn run webpack
  - cp -r src/* dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master