image: node:alpine

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apk add --update curl git ssh
          - yarn install
          - yarn run webpack
          - cp -r src/* dist
          - export DIST_NAME=../${BITBUCKET_BRANCH}_${BITBUCKET_COMMIT}.tar.gz
          - tar czf $DIST_NAME -C dist .
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$DIST_NAME"
          - cp -r dist .. && cd ../dist
          - git init && git remote add origin git@github.com:wkevina/webgl-pages
          - git config --global user.email "antiomiae@gmail.com" && git config --global user.name "Kevin Ward"
          - git checkout -b gh-pages && git add . && git commit -m . && git push --force origin gh-pages
